### ISSUE TITLE
最新的代码，发送消息闪退。

### ISSUE THREAD

**Issue by captain-miao** [wildfirechat/hm-chat#47]
就是最新的官方代码，卸载/重新安装也一样。
```
Reason:TypeError
Error name:TypeError
Error message:Cannot read property type of undefined
Stacktrace:
    at anonymous (oh_modules/.ohpm/@wfc+avenginekit@rslinak+clkr+fzsaszydxi6zoqbvmgam+qftijvgwc=/oh_modules/@wfc/avenginekit/src/main/ets/wfc/av/a/b.js:25:1)
    at emit (/usr1/hmos_for_system/src/increment/sourcecode/foundation/ability/ability_runtime/frameworks/js/napi/app/context/context.js:61:1)
    at onReceiveMessage (client/src/main/ets/wfc/proto/proto.min.ets:154:13)
```

**Comment by imndx** [comment]
你把项目下的所有`oh_modules`目录删除，然后重试一下

**Comment by captain-miao** [comment]
> 你把项目下的所有`oh_modules`目录删除，然后重试一下

好了。
1. 删除 oh_modules 目录
2. clean
3. rebuild
4. run

**Comment by captain-miao** [comment]
> > 你把项目下的所有`oh_modules`目录删除，然后重试一下
> 
> 发送文字消息好了。
> 
> 1. 删除 oh_modules 目录
> 2. clean
> 3. rebuild
> 4. run

但是发送图片，闪退了。

`Error message:the parameters check fails   Parameter verification failed, GetInternalPath failed, filePath is not valid

Error code:
Stacktrace:

    at anonymous (client/src/main/ets/wfc/proto/proto.min.ets:2361:17)`

**Comment by imndx** [comment]
已修复，请查看最新提交
